### ISSUE TITLE
[TextMate] treat tag annotations as comments

### ISSUE THREAD

**Issue by DavyLandman** [usethesource/rascal-syntax-highlighting#10]
Most files contain a license header, and a lot of standard functions contain documentation tags.
The body of them should be marked as comments.

```rascal
@license{
  BSD-2 License
}
module A

@doc{
   Textile markup for the documentation
}
@javaClass{org.rascalmpl.library.X}
public java str doStuff(int x);
```

they should be marked as comments instead of normal text

**Comment by ahmadsalim** [comment]
[New example](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgist.githubusercontent.com%2Fahmadsalim%2F5b01f22e788264860ff6b4ca07007417%2Fraw%2F236478e23e9c766f24830cdad0b376b9a8ad9b9b%2FRascal.tmLanguage&grammar_text=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0D%0A%3C%21DOCTYPE+plist+PUBLIC+%22-%2F%2FApple%2F%2FDTD+PLIST+1.0%2F%2FEN%22+%22http%3A%2F%2Fwww.apple.com%2FDTDs%2FPropertyList-1.0.dtd%22%3E%0D%0A%3Cplist+version%3D%221.0%22%3E%0D%0A%3Cdict%3E%0D%0A%09%3Ckey%3EfileTypes%3C%2Fkey%3E%0D%0A%09%3Carray%3E%0D%0A%09%09%3Cstring%3Ersc%3C%2Fstring%3E%0D%0A%09%3C%2Farray%3E%0D%0A%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%3Cstring%3ERascal%3C%2Fstring%3E%0D%0A%09%3Ckey%3Epatterns%3C%2Fkey%3E%0D%0A%09%3Carray%3E%0D%0A%09%09%3Cdict%3E%0D%0A%09%09%09%3Ckey%3Ematch%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%2F%2F.*%24%5Cn%3F%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3Ecomment.line.double-slash.rascal%3C%2Fstring%3E%0D%0A%09%09%3C%2Fdict%3E%0D%0A%09%09%3Cdict%3E%0D%0A%09%09%09%3Ckey%3Ebegin%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%2F%5C*%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Eend%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%5C*%2F%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3Ecomment.block.rascal%3C%2Fstring%3E%0D%0A%09%09%3C%2Fdict%3E%0D%0A%09%3C%2Farray%3E%0D%0A%09%3Ckey%3EscopeName%3C%2Fkey%3E%0D%0A%09%3Cstring%3Esource.rascal%3C%2Fstring%3E%0D%0A%09%3Ckey%3Euuid%3C%2Fkey%3E%0D%0A%09%3Cstring%3E6d5574d4-85af-4e00-9f3c-9b5fa60f53b8%3C%2Fstring%3E%0D%0A%3C%2Fdict%3E%0D%0A%3C%2Fplist%3E&code_source=from-text&code_url=https%3A%2F%2Fgithub.com%2Fusethesource%2Frascal%2Fblob%2F56b48973b85ab0770cd7abe04c45a5d6b9ebe109%2Fsrc%2Forg%2Frascalmpl%2Flibrary%2Flang%2Frascal%2Fsyntax%2FRascal.rsc&code=%40license%7B%0D%0A++BSD-2+License%0D%0A%7D%0D%0Amodule+A%0D%0A%0D%0A%40doc%7B%0D%0A+++Textile+markup+for+the+documentation%0D%0A%7D%0D%0A%40javaClass%7Borg.rascalmpl.library.X%7D%0D%0Apublic+java+str+doStuff%28int+x%29%3B)

**Comment by PaulKlint** [comment]
Nice!
