### ISSUE TITLE
[TextMate] two slashes inside a source locations are considered comments when the authority contains dashes

### ISSUE THREAD

**Issue by DavyLandman** [usethesource/rascal-syntax-highlighting#11]
```rascal
loc working = |scheme://normal/as/it/should/be|;
loc broken = |scheme://with-dashes-in-authority/breaks/it|;
```

**Comment by ahmadsalim** [comment]
Ups, I forgot to escape the dash inside the character sets. If you want, you can assign me and I will look at it in the weekend.

**Comment by DavyLandman** [comment]
It seems I can't assign you, you are not (yet?) a member of the usethesource organization. Pinging @jurgenvinju to see how we deal with this.

So, good to know you'll take a look at this. :+1:

Could you put a small readme in the dir on how to generate the `.tmLanguage` file from the `YAML` file?

**Comment by ahmadsalim** [comment]
> It seems I can't assign you, you are not (yet?) a member of the usethesource organization. Pinging @jurgenvinju to see how we deal with this.

Ah, I see. I thought you could put a per repository team.

**Comment by DavyLandman** [comment]
you are right, you've been invited.

**Comment by ahmadsalim** [comment]
@DavyLandman Thanks! I have assigned myself.

**Comment by ahmadsalim** [comment]
[New example](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgist.githubusercontent.com%2Fahmadsalim%2F5b01f22e788264860ff6b4ca07007417%2Fraw%2F2fbc803bbb6a0f3ff74c9d4e9e3dde7484396df6%2FRascal.tmLanguage&grammar_text=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0D%0A%3C%21DOCTYPE+plist+PUBLIC+%22-%2F%2FApple%2F%2FDTD+PLIST+1.0%2F%2FEN%22+%22http%3A%2F%2Fwww.apple.com%2FDTDs%2FPropertyList-1.0.dtd%22%3E%0D%0A%3Cplist+version%3D%221.0%22%3E%0D%0A%3Cdict%3E%0D%0A%09%3Ckey%3EfileTypes%3C%2Fkey%3E%0D%0A%09%3Carray%3E%0D%0A%09%09%3Cstring%3Ersc%3C%2Fstring%3E%0D%0A%09%3C%2Farray%3E%0D%0A%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%3Cstring%3ERascal%3C%2Fstring%3E%0D%0A%09%3Ckey%3Epatterns%3C%2Fkey%3E%0D%0A%09%3Carray%3E%0D%0A%09%09%3Cdict%3E%0D%0A%09%09%09%3Ckey%3Ematch%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%2F%2F.*%24%5Cn%3F%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3Ecomment.line.double-slash.rascal%3C%2Fstring%3E%0D%0A%09%09%3C%2Fdict%3E%0D%0A%09%09%3Cdict%3E%0D%0A%09%09%09%3Ckey%3Ebegin%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%2F%5C*%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Eend%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%5C*%2F%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3Ecomment.block.rascal%3C%2Fstring%3E%0D%0A%09%09%3C%2Fdict%3E%0D%0A%09%3C%2Farray%3E%0D%0A%09%3Ckey%3EscopeName%3C%2Fkey%3E%0D%0A%09%3Cstring%3Esource.rascal%3C%2Fstring%3E%0D%0A%09%3Ckey%3Euuid%3C%2Fkey%3E%0D%0A%09%3Cstring%3E6d5574d4-85af-4e00-9f3c-9b5fa60f53b8%3C%2Fstring%3E%0D%0A%3C%2Fdict%3E%0D%0A%3C%2Fplist%3E&code_source=from-text&code_url=https%3A%2F%2Fgithub.com%2Fusethesource%2Frascal%2Fblob%2F56b48973b85ab0770cd7abe04c45a5d6b9ebe109%2Fsrc%2Forg%2Frascalmpl%2Flibrary%2Flang%2Frascal%2Fsyntax%2FRascal.rsc&code=loc+working+%3D+%7Cscheme%3A%2F%2Fnormal%2Fas%2Fit%2Fshould%2Fbe%7C%3B%0D%0Aloc+broken+%3D+%7Cscheme%3A%2F%2Fwith-dashes-in-authority%2Fbreaks%2Fit%7C%3B)
