### ISSUE TITLE
Distinguish between lexical character sets and list literals

### ISSUE THREAD

**Issue by ahmadsalim** [usethesource/rascal-syntax-highlighting#5]
Currently all elements between two brackets `[]` are treated naïvely as lexical character set, which results in issues with highlighting list literals. Particularly, we must ensure that only things between brackets inside `lexical` or `syntax` scopes are treated as character sets, and those outside are treated as list literals.

Note that removing the support for lexical character sets ruins the highlighting of the rest of the programs since `\"` and "/", and other similar characters can appear freely in character set expressions.

Examples of mis-highlighted terms:

```rascal
// comment 1

n = 1;  // comment 2
l = [1, // comment 3: non highlighted
     2, 
     3];
```

```rascal
list[int] n
```

```rascal
private MuExp translateStringLiteral(s: (StringLiteral) `<PreStringChars pre> <Expression expression> <StringTail tail>`) {
    preIndent = computeIndent(pre);
    return muBlock( [ muCallPrim3("template_open", translatePreChars(pre), pre@\loc),
    				  *translateExpInStringLiteral(preIndent, expression),
    				  *translateTail(preIndent, tail),
    				  muCallPrim3("template_close", [], tail@\loc)
					]   );
}
```

**Comment by ahmadsalim** [comment]
OK, I have tried to fix the issues now:

[First Example](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgist.githubusercontent.com%2Fahmadsalim%2F5b01f22e788264860ff6b4ca07007417%2Fraw%2F41d2924fd6c01c517e9b69480c2d56208feacc7a%2FRascal.tmLanguage&grammar_text=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0D%0A%3C%21DOCTYPE+plist+PUBLIC+%22-%2F%2FApple%2F%2FDTD+PLIST+1.0%2F%2FEN%22+%22http%3A%2F%2Fwww.apple.com%2FDTDs%2FPropertyList-1.0.dtd%22%3E%0D%0A%3Cplist+version%3D%221.0%22%3E%0D%0A%3Cdict%3E%0D%0A%09%3Ckey%3EfileTypes%3C%2Fkey%3E%0D%0A%09%3Carray%3E%0D%0A%09%09%3Cstring%3Ersc%3C%2Fstring%3E%0D%0A%09%3C%2Farray%3E%0D%0A%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%3Cstring%3ERascal%3C%2Fstring%3E%0D%0A%09%3Ckey%3Epatterns%3C%2Fkey%3E%0D%0A%09%3Carray%3E%0D%0A%09%09%3Cdict%3E%0D%0A%09%09%09%3Ckey%3Ematch%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%2F%2F.*%24%5Cn%3F%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3Ecomment.line.double-slash.rascal%3C%2Fstring%3E%0D%0A%09%09%3C%2Fdict%3E%0D%0A%09%09%3Cdict%3E%0D%0A%09%09%09%3Ckey%3Ebegin%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%2F%5C*%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Eend%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%5C*%2F%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3Ecomment.block.rascal%3C%2Fstring%3E%0D%0A%09%09%3C%2Fdict%3E%0D%0A%09%3C%2Farray%3E%0D%0A%09%3Ckey%3EscopeName%3C%2Fkey%3E%0D%0A%09%3Cstring%3Esource.rascal%3C%2Fstring%3E%0D%0A%09%3Ckey%3Euuid%3C%2Fkey%3E%0D%0A%09%3Cstring%3E6d5574d4-85af-4e00-9f3c-9b5fa60f53b8%3C%2Fstring%3E%0D%0A%3C%2Fdict%3E%0D%0A%3C%2Fplist%3E&code_source=from-text&code_url=https%3A%2F%2Fgithub.com%2Fusethesource%2Frascal%2Fblob%2F56b48973b85ab0770cd7abe04c45a5d6b9ebe109%2Fsrc%2Forg%2Frascalmpl%2Flibrary%2Flang%2Frascal%2Fsyntax%2FRascal.rsc&code=%2F%2F+comment+1%0D%0A%0D%0An+%3D+1%3B++%2F%2F+comment+2%0D%0Al+%3D+%5B1%2C+%2F%2F+comment+3%3A+non+highlighted%0D%0A+++++2%2C+%0D%0A+++++3%5D%3B)

[Second Example](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgist.githubusercontent.com%2Fahmadsalim%2F5b01f22e788264860ff6b4ca07007417%2Fraw%2F41d2924fd6c01c517e9b69480c2d56208feacc7a%2FRascal.tmLanguage&grammar_text=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0D%0A%3C%21DOCTYPE+plist+PUBLIC+%22-%2F%2FApple%2F%2FDTD+PLIST+1.0%2F%2FEN%22+%22http%3A%2F%2Fwww.apple.com%2FDTDs%2FPropertyList-1.0.dtd%22%3E%0D%0A%3Cplist+version%3D%221.0%22%3E%0D%0A%3Cdict%3E%0D%0A%09%3Ckey%3EfileTypes%3C%2Fkey%3E%0D%0A%09%3Carray%3E%0D%0A%09%09%3Cstring%3Ersc%3C%2Fstring%3E%0D%0A%09%3C%2Farray%3E%0D%0A%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%3Cstring%3ERascal%3C%2Fstring%3E%0D%0A%09%3Ckey%3Epatterns%3C%2Fkey%3E%0D%0A%09%3Carray%3E%0D%0A%09%09%3Cdict%3E%0D%0A%09%09%09%3Ckey%3Ematch%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%2F%2F.*%24%5Cn%3F%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3Ecomment.line.double-slash.rascal%3C%2Fstring%3E%0D%0A%09%09%3C%2Fdict%3E%0D%0A%09%09%3Cdict%3E%0D%0A%09%09%09%3Ckey%3Ebegin%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%2F%5C*%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Eend%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%5C*%2F%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3Ecomment.block.rascal%3C%2Fstring%3E%0D%0A%09%09%3C%2Fdict%3E%0D%0A%09%3C%2Farray%3E%0D%0A%09%3Ckey%3EscopeName%3C%2Fkey%3E%0D%0A%09%3Cstring%3Esource.rascal%3C%2Fstring%3E%0D%0A%09%3Ckey%3Euuid%3C%2Fkey%3E%0D%0A%09%3Cstring%3E6d5574d4-85af-4e00-9f3c-9b5fa60f53b8%3C%2Fstring%3E%0D%0A%3C%2Fdict%3E%0D%0A%3C%2Fplist%3E&code_source=from-text&code_url=https%3A%2F%2Fgithub.com%2Fusethesource%2Frascal%2Fblob%2F56b48973b85ab0770cd7abe04c45a5d6b9ebe109%2Fsrc%2Forg%2Frascalmpl%2Flibrary%2Flang%2Frascal%2Fsyntax%2FRascal.rsc&code=list%5Bint%5D+n)

[Third Example](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgist.githubusercontent.com%2Fahmadsalim%2F5b01f22e788264860ff6b4ca07007417%2Fraw%2F41d2924fd6c01c517e9b69480c2d56208feacc7a%2FRascal.tmLanguage&grammar_text=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0D%0A%3C%21DOCTYPE+plist+PUBLIC+%22-%2F%2FApple%2F%2FDTD+PLIST+1.0%2F%2FEN%22+%22http%3A%2F%2Fwww.apple.com%2FDTDs%2FPropertyList-1.0.dtd%22%3E%0D%0A%3Cplist+version%3D%221.0%22%3E%0D%0A%3Cdict%3E%0D%0A%09%3Ckey%3EfileTypes%3C%2Fkey%3E%0D%0A%09%3Carray%3E%0D%0A%09%09%3Cstring%3Ersc%3C%2Fstring%3E%0D%0A%09%3C%2Farray%3E%0D%0A%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%3Cstring%3ERascal%3C%2Fstring%3E%0D%0A%09%3Ckey%3Epatterns%3C%2Fkey%3E%0D%0A%09%3Carray%3E%0D%0A%09%09%3Cdict%3E%0D%0A%09%09%09%3Ckey%3Ematch%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%2F%2F.*%24%5Cn%3F%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3Ecomment.line.double-slash.rascal%3C%2Fstring%3E%0D%0A%09%09%3C%2Fdict%3E%0D%0A%09%09%3Cdict%3E%0D%0A%09%09%09%3Ckey%3Ebegin%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%2F%5C*%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Eend%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%5C*%2F%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3Ecomment.block.rascal%3C%2Fstring%3E%0D%0A%09%09%3C%2Fdict%3E%0D%0A%09%3C%2Farray%3E%0D%0A%09%3Ckey%3EscopeName%3C%2Fkey%3E%0D%0A%09%3Cstring%3Esource.rascal%3C%2Fstring%3E%0D%0A%09%3Ckey%3Euuid%3C%2Fkey%3E%0D%0A%09%3Cstring%3E6d5574d4-85af-4e00-9f3c-9b5fa60f53b8%3C%2Fstring%3E%0D%0A%3C%2Fdict%3E%0D%0A%3C%2Fplist%3E&code_source=from-text&code_url=https%3A%2F%2Fgithub.com%2Fusethesource%2Frascal%2Fblob%2F56b48973b85ab0770cd7abe04c45a5d6b9ebe109%2Fsrc%2Forg%2Frascalmpl%2Flibrary%2Flang%2Frascal%2Fsyntax%2FRascal.rsc&code=private+MuExp+translateStringLiteral%28s%3A+%28StringLiteral%29+%60%3CPreStringChars+pre%3E+%3CExpression+expression%3E+%3CStringTail+tail%3E%60%29+%7B%0D%0A++++preIndent+%3D+computeIndent%28pre%29%3B%0D%0A++++return+muBlock%28+%5B+muCallPrim3%28%22template_open%22%2C+translatePreChars%28pre%29%2C+pre%40%5Cloc%29%2C%0D%0A++++%09%09%09%09++*translateExpInStringLiteral%28preIndent%2C+expression%29%2C%0D%0A++++%09%09%09%09++*translateTail%28preIndent%2C+tail%29%2C%0D%0A++++%09%09%09%09++muCallPrim3%28%22template_close%22%2C+%5B%5D%2C+tail%40%5Cloc%29%0D%0A%09%09%09%09%09%5D+++%29%3B%0D%0A%7D)

Non-regression: [Grammar](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgist.githubusercontent.com%2Fahmadsalim%2F5b01f22e788264860ff6b4ca07007417%2Fraw%2F41d2924fd6c01c517e9b69480c2d56208feacc7a%2FRascal.tmLanguage&grammar_text=%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E%0D%0A%3C%21DOCTYPE+plist+PUBLIC+%22-%2F%2FApple%2F%2FDTD+PLIST+1.0%2F%2FEN%22+%22http%3A%2F%2Fwww.apple.com%2FDTDs%2FPropertyList-1.0.dtd%22%3E%0D%0A%3Cplist+version%3D%221.0%22%3E%0D%0A%3Cdict%3E%0D%0A%09%3Ckey%3EfileTypes%3C%2Fkey%3E%0D%0A%09%3Carray%3E%0D%0A%09%09%3Cstring%3Ersc%3C%2Fstring%3E%0D%0A%09%3C%2Farray%3E%0D%0A%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%3Cstring%3ERascal%3C%2Fstring%3E%0D%0A%09%3Ckey%3Epatterns%3C%2Fkey%3E%0D%0A%09%3Carray%3E%0D%0A%09%09%3Cdict%3E%0D%0A%09%09%09%3Ckey%3Ematch%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%2F%2F.*%24%5Cn%3F%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3Ecomment.line.double-slash.rascal%3C%2Fstring%3E%0D%0A%09%09%3C%2Fdict%3E%0D%0A%09%09%3Cdict%3E%0D%0A%09%09%09%3Ckey%3Ebegin%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%2F%5C*%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Eend%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3E%5C*%2F%3C%2Fstring%3E%0D%0A%09%09%09%3Ckey%3Ename%3C%2Fkey%3E%0D%0A%09%09%09%3Cstring%3Ecomment.block.rascal%3C%2Fstring%3E%0D%0A%09%09%3C%2Fdict%3E%0D%0A%09%3C%2Farray%3E%0D%0A%09%3Ckey%3EscopeName%3C%2Fkey%3E%0D%0A%09%3Cstring%3Esource.rascal%3C%2Fstring%3E%0D%0A%09%3Ckey%3Euuid%3C%2Fkey%3E%0D%0A%09%3Cstring%3E6d5574d4-85af-4e00-9f3c-9b5fa60f53b8%3C%2Fstring%3E%0D%0A%3C%2Fdict%3E%0D%0A%3C%2Fplist%3E&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fusethesource%2Frascal%2Fblob%2F56b48973b85ab0770cd7abe04c45a5d6b9ebe109%2Fsrc%2Forg%2Frascalmpl%2Flibrary%2Flang%2Frascal%2Fsyntax%2FRascal.rsc&code=https%3A%2F%2Fgithub.com%2Fusethesource%2Frascal%2Fblob%2F56b48973b85ab0770cd7abe04c45a5d6b9ebe109%2Fsrc%2Forg%2Frascalmpl%2Flibrary%2Flang%2Frascal%2Fsyntax%2FRascal.rsc)

I apologise for it taking a bit of time, but I had used a lot of time debugging things because I misunderstood a part of how the syntax highlighting matched over newlines (apparently a single pattern using `match` is only run for a single line, `begin` and `end` work with newlines).

**Comment by DavyLandman** [comment]
You are making great progress!

Perhaps update the pull request on the linguist library? to point to this newer version?

**Comment by PaulKlint** [comment]
I have tried to highlight two dozen fragments of complex Rascal code and so far I have not yet spotted irregularities. Great work. This is rapidly becoming very useful.

**Comment by ahmadsalim** [comment]
Great, thanks for the comments.

@DavyLandman I think they use git submodules, so it should synchronise automatically I hope.

**Comment by DavyLandman** [comment]
git submodules point to a specific commit in the history, so you'll have to update which commit it points to ([see here](https://github.com/github/linguist/pull/3352/files#diff-537f399e9140b9ace8bc83319c0b972d)).

You'll have to go into the `vendor/grammars/rascal-syntax-highlighting` directory, perform a `git pull`, go back to the root of the linguist folder and commit the changes (git status will show the pointer to the commit has moved)

**Comment by ahmadsalim** [comment]
@DavyLandman OK, done.
